workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    merge-code-samples-into-spec:
        inputs:
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/openapi
        overlays:
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-typescript-first-target:main
            - location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/code-samples-go-speakeasy-client-sdk-go:main
        output: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/merge-code-samples-into-spec
targets: {}
